export const REGIONS_CHILE = [
  { id: "arica", name: "Arica y Parinacota" },
  { id: "tarapaca", name: "Tarapacá" },
  { id: "antofagasta", name: "Antofagasta" },
  { id: "atacama", name: "Atacama" },
  { id: "coquimbo", name: "Coquimbo" },
  { id: "valparaiso", name: "Valparaíso" },
  { id: "metropolitana", name: "Metropolitana de Santiago" },
  { id: "ohiggins", name: "O'Higgins" },
  { id: "maule", name: "Maule" },
  { id: "nuble", name: "Ñuble" },
  { id: "biobio", name: "Biobío" },
  { id: "araucania", name: "La Araucanía" },
  { id: "losrios", name: "Los Ríos" },
  { id: "loslagos", name: "Los Lagos" },
  { id: "aysen", name: "Aysén" },
  { id: "magallanes", name: "Magallanes" },
];
